services:
  - type: web
    name: musicplayer
    env: python
    buildCommand: ""
    startCommand: gunicorn mymusicplayer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mymusicplayer.settings
      - key: PYTHON_VERSION
        value: 3.10
