# Generated by Django 5.1.1 on 2024-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album_cover', models.ImageField(upload_to='Album Covers/')),
                ('music_file', models.FileField(upload_to='music/')),
            ],
        ),
    ]
